# Array Mathematics

In [1]:
import numpy as np
N , M =map(int,input().split())
A , B =(np.array([input().strip().split() for _ in range(N)],int) for _ in range(2))
print (np.add(A, B))
print (np.subtract(A, B))
print (np.multiply(A, B))
print ( A//B )
print (np.mod(A, B))
print (np.power(A, B))

1 3
2 2 2
3 3 3
[[5 5 5]]
[[-1 -1 -1]]
[[6 6 6]]
[[0 0 0]]
[[2 2 2]]
[[8 8 8]]
