# Floor,Ceil and Rint

In [1]:
import numpy
numpy.set_printoptions(sign=' ') #To more spaces

a = numpy.array(input().split(),float)
print( numpy.floor(a))      
print( numpy.ceil(a))  
print( numpy.rint(a))  

1.2 6.5 3.2 9.8 4.2 6.5
[ 1.  6.  3.  9.  4.  6.]
[  2.   7.   4.  10.   5.   7.]
[  1.   6.   3.  10.   4.   6.]
