# Ones and Zros

In [5]:
import numpy
#N=map(int,input().split())
nums = tuple(map(int, input().split()))

print (numpy.zeros(nums, dtype = numpy.int) )
print (numpy.ones(nums, dtype = numpy.int) )

4 2 5
[[[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]]
[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]
