# Transpose and Flatten



In [7]:
import numpy as np
N ,M = map(int,input().split())
s = np.array([input().strip().split() for _ in range(N)], int)
print(s.transpose())
print(s.flatten())
#print(np.flatten(s)) 

2 2
5 6
8 9
[[5 8]
 [6 9]]
[[5 8]
 [6 9]]
[5 6 8 9]
